export {default as LoginPage} from './LoginPage'
export {default as PointPage} from './PointPage'
export {default as RegisterPage} from './RegisterPage'
export {default as WishListPage} from './WishListPage'
export {default as MyPage} from './MyPage'