export {default as Home} from './Home'
export {default as IntroPage} from './IntroPage'
export {default as ActivityAdmin} from './ActivityAdmin'
export {default as LoginPage} from '../Home/LoginPage'
export {default as RegisterPage} from './RegisterPage'